apiVersion: v1
kind: Service
metadata:
  name: jenkins-ui
  labels:
    app: jenkins
spec:
  selector:
    app: master
  type: NodePort
  ports:
  - name: ui
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-discovery
  labels:
    app: jenkins
spec:
  selector:
    app: master
  ports:
  - name: slaves
    port: 5000
    targetPort: 5000
