apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
      jenkins: master
      env: prod
  serviceName: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
        jenkins: master
        env: prod
    spec:
      serviceAccountName: jenkins
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: master
        image: jenkins/jenkins:2.67
        ports:
        - containerPort: 8080
        - containerPort: 50000
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        env:
        - name: JAVA_OPTS
          value: '-Xmx1400m'
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 1500Mi
  volumeClaimTemplates:
   - metadata:
       name: jenkins-home
       labels:
         env: prod
     spec:
       accessModes: ["ReadWriteOnce"]
       storageClassName: "fast" # StorageOS storageClass 
       resources:
         requests:
           storage: 10Gi
